### ISSUE TITLE
Help on how to properly run it on Fedora

### ISSUE THREAD

**Issue by doceazedo** [wnayes/electron-wm#2]
Hi! First of all, I'm a Linux newbie just really curious to know how this works. I've built and ran it successfully but with a few issues and questions:

I think it is "conflicting" with GNOME, somehow? I tried opening Firefox and it is rendering with the GNOME topbar. I guess the expected behavior was to it render with a topbar similar to that on the README screenshot, right?
![image](https://user-images.githubusercontent.com/33992396/176084708-4b339beb-7e5b-40f3-b846-1b759a7dc45f.png)

Also, GNOME probably shouldn't even be running alongside electron-wm. Is there a way to disable it before opening electron-wm? Or maybe add electron-wm to the window manager selector on the login screen? I'm pretty sure I'm missing something here... 😅

With those questions answered I'll probably be able to guess how to properly run it in fullscreen.

Thanks in advance for your patience! This is a really neat project. ✨

**Comment by wnayes** [comment]
It looks like you launched the window manager inside Xephyr, which is typically just used for development or experimentation. You'd have to not run GNOME, and run the window manager instead, like you said.

I am not sure whether Firefox on Fedora will continue to look like this when the window manager is ran by itself. Some windows can choose to draw their own title bar. That doesn't happen for my Firefox install, but it could be different here.

I think you would want to set up the login screen to have an option to use this window manager to use it for real. I am not familiar with Fedora setup, but this post seems helpful:
https://superuser.com/questions/667042/fedora-window-manager-list

Thanks for trying it out!
