### ISSUE TITLE
Tray

### ISSUE THREAD

**Issue by danielmeloalencar** [wnayes/electron-wm#4]
System tray works?
Do you intend to make it work?

**Comment by wnayes** [comment]
System tray support would be nice, but I haven't ran into a program myself yet where there is a tray icon. I tried Dropbox I recall, but I wasn't able to figure out at the time what window messages to look out for.

Do you have any examples of programs that use a tray that could help test this?

**Comment by danielmeloalencar** [comment]
Discord, Obs Studio

**Comment by wnayes** [comment]
I added some basic system tray icon support in f2e2a122. There is an issue with icon transparency I haven't sorted out yet. I used OBS as the test case and as far as I have seen, the basic functionality seems to be working.

**Comment by danielmeloalencar** [comment]
Perfect

**Comment by wnayes** [comment]
Closing issue - any specific issues with the new tray support can be filed as separate issues.
